config/routes.rb
Rails.application.routes.draw do
  resources :filmes
  resources :ators
  resources :criticas
  resources :logs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "filmes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ator.rb
class Ator < ApplicationRecord

    validates :nome, :ano_nascimento, :email, presence: true
    validates :email, uniqueness: true
end

app/models/critica.rb
class Critica < ApplicationRecord
  belongs_to :Filme

  default_scope { where(esta_aprovado: true ) }
  
  validates :comentario, :Filme, presence: true

  
end

app/models/filme.rb
class Filme < ApplicationRecord
  belongs_to :ator
   validates :titulo, :ano_lancamento, :ator, presence: true
   validates :titulo, uniqueness: true
end

app/models/log.rb
class Log < ApplicationRecord

    validates :comentario_id, presence: true

    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ators_controller.rb
class AtorsController < ApplicationController
  before_action :set_ator, only: %i[ show edit update destroy ]
  before_action :set_filme, only: %i[ show edit update destroy ]

  # GET /ators or /ators.json
  def index
    @ators = Ator.all
  end

  # GET /ators/1 or /ators/1.json
  def show
  end

  # GET /ators/new
  def new
    @ator = Ator.new
  end

  # GET /ators/1/edit
  def edit
  end

  # POST /ators or /ators.json
  def create
    @ator = Ator.new(ator_params)

    respond_to do |format|
      if @ator.save
        format.html { redirect_to ator_url(@ator), notice: "Ator was successfully created." }
        format.json { render :show, status: :created, location: @ator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ators/1 or /ators/1.json
  def update
    respond_to do |format|
      if @ator.update(ator_params)
        format.html { redirect_to ator_url(@ator), notice: "Ator was successfully updated." }
        format.json { render :show, status: :ok, location: @ator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ators/1 or /ators/1.json
  def destroy
    @ator.destroy

    respond_to do |format|
      format.html { redirect_to ators_url, notice: "Ator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_filme
      @filme = Filme.find(params[:id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_ator
      @ator = Ator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ator_params
      params.require(:ator).permit(:nome, :ano_nascimento, :email)
    end
end

app/controllers/criticas_controller.rb
class CriticasController < ApplicationController
  before_action :set_critica, only: %i[ show edit update destroy ]
  before_action :set_filme, only: %i[new show edit create update ]
  

  # GET /criticas or /criticas.json
  def index
    @criticas = Critica.all
  end

  # GET /criticas/1 or /criticas/1.json
  def show

    
  end

  # GET /criticas/new
  def new
    @critica = Critica.new
    @critica.esta_aprovado = true
  end

  # GET /criticas/1/edit
  def edit
  end

  # POST /criticas or /criticas.json
  def create
    @critica = Critica.new(critica_params)
    

    

    respond_to do |format|
      if @critica.save
        format.html { redirect_to critica_url(@critica), notice: "Comentário feito com sucesso! Aguarde aprovação." }
        format.json { render :show, status: :created, location: @critica }

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @critica.errors, status: :unprocessable_entity }
      end
      
    end

   end

  # PATCH/PUT /criticas/1 or /criticas/1.json
  
  def update
    
    respond_to do |format|
      if @critica.update(critica_params)
        format.html { redirect_to critica_url(@critica), notice: "Comentário Aprovado!" }
        format.json { render :show, status: :ok, location: @critica }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @critica.errors, status: :unprocessable_entity }
      end
    end
    
    if @critica.esta_aprovado == true
    a = Log.new
    a.comentario_id = params[:id]
    a.save
    end
end

  # DELETE /criticas/1 or /criticas/1.json
  def destroy
    @critica.destroy

    respond_to do |format|
      format.html { redirect_to criticas_url, notice: "Comentário apagado com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filme
      @filme = Filme.all.pluck(:titulo,:id)
    end
        
    def set_critica
      @critica = Critica.find(params[:id])
    end
    def set_filme
      @filme= Filme.all.pluck(:titulo,:id)
    end

    # Only allow a list of trusted parameters through.
    def critica_params
      params.require(:critica).permit(:comentario, :esta_aprovado, :Filme_id)
    end
end

app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: %i[ show edit update destroy ]
  before_action :set_ator, only: %i[new show edit create update ]

  # GET /filmes or /filmes.json
  def index
    @filmes = Filme.all
  end

  # GET /filmes/1 or /filmes/1.json
  def show
  end

  # GET /filmes/new
  def new
    @filme = Filme.new
    
  end

  # GET /filmes/1/edit
  def edit
  end

  # POST /filmes or /filmes.json
  def create
    @filme = Filme.new(filme_params)

    respond_to do |format|
      if @filme.save
        format.html { redirect_to filme_url(@filme), notice: "Filme Adicionado." }
        format.json { render :show, status: :created, location: @filme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filmes/1 or /filmes/1.json
  def update
    respond_to do |format|
      if @filme.update(filme_params)
        format.html { redirect_to filme_url(@filme), notice: "Filme Editado" }
        format.json { render :show, status: :ok, location: @filme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filmes/1 or /filmes/1.json
  def destroy
    @filme.destroy

    respond_to do |format|
      format.html { redirect_to filmes_url, notice: "Filme Excluído!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ator
      @ator= Ator.all.pluck(:nome,:id)
    end 
    def set_filme
      @filme = Filme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def filme_params
      params.require(:filme).permit(:titulo, :ano_lancamento, :ator_id)
    end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
    def index
        @logs = Log.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ators_helper.rb
module AtorsHelper
end

app/helpers/criticas_helper.rb
module CriticasHelper
end

app/helpers/filmes_helper.rb
module FilmesHelper
end

app/views/ators/_ator.html.erb
<div id="<%= dom_id ator %>">
  <p>
    <strong>Nome:</strong>
    <%= ator.nome %>
  </p>

  <p>
    <strong>Ano nascimento:</strong>
    <%= ator.ano_nascimento %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= ator.email %>
  </p>

</div>

app/views/ators/_form.html.erb
<%= form_with(model: ator) do |form| %>
  <% if ator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ator.errors.count, "error") %> prohibited this ator from being saved:</h2>

      <ul>
        <% ator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :ano_nascimento, style: "display: block" %>
    <%= form.number_field :ano_nascimento %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ators/edit.html.erb
<div class="shadow-none p-3 mb-5 bg-light rounded">Editar</div>

<%= render "form", ator: @ator %>

<br>

<div>
  <%= link_to "Show this ator", @ator %> |
  <%= link_to "Back to ators", ators_path %>
</div>

app/views/ators/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="shadow-none p-3 mb-5 bg-light rounded">Ator</div>


<div id="ators">
  <% @ators.each do |ator| %>
    <%= render ator %>
    <p>
      <%= link_to "Show this ator", ator %>
    </p>
  <% end %>
</div>

<%= link_to "Novo Ator", new_ator_path %>

app/views/ators/new.html.erb
<div class="shadow-none p-3 mb-5 bg-light rounded">Novo Filme</div>


<%= render "form", ator: @ator %>

<br>

<div>
  <%= link_to "Back to ators", ators_path %>
</div>

app/views/ators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ator %>

<div>
  <%= link_to "Edit this ator", edit_ator_path(@ator) %> |
  <%= link_to "Back to ators", ators_path %>

  <%= button_to "Destroy this ator", @ator, method: :delete %>
</div>

app/views/criticas/_critica.html.erb
<div id="<%= dom_id critica %>">
  <p>
    <strong>Comentario:</strong>
    <%= critica.comentario %>
  </p>

  <p hidden>
    <strong>Esperando aprovação...</strong>
    <%= critica.esta_aprovado %>
  </p>

  <p>
    <strong>Filme:</strong>
    <%= critica.Filme_id %>
  </p>

</div>

app/views/criticas/_form.html.erb
<%= form_with(model: critica) do |form| %>
  <% if critica.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(critica.errors.count, "error") %> prohibited this critica from being saved:</h2>

      <ul>
        <% critica.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :comentario, style: "display: block" %>
    <%= form.text_area :comentario %>
  </div>

  <div hidden>
    <%= form.label :esta_aprovado, style: "display: block" %>
   <%= form.check_box :esta_aprovado %>
  </div>

  <div>
    <%= form.label :Filme_id, style: "display: block" %>
    <%= form.select(:Filme_id,@filme,{},{}) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/criticas/edit.html.erb
<div class="shadow-none p-3 mb-5 bg-light rounded">Aprovar Comentário</div>

<%= render "form", critica: @critica %>

<br>

<div>
  <%= link_to "Mostrar este comentário", @critica %> |
  <%= link_to "Voltar aos comentários", criticas_path %>
</div>

app/views/criticas/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="shadow-none p-3 mb-5 bg-light rounded">Críticas</div>


<div id="criticas">
  <% @criticas.each do |critica| %>
    <%= render critica %>
    <p>
      <%= link_to "Mostrar comentário", critica %>
    </p>
  <% end %>
</div>

<%= link_to "Novo comentário", new_critica_path %>

app/views/criticas/new.html.erb
<div class="shadow-none p-3 mb-5 bg-light rounded">Novo Filme</div>


<%= render "form", critica: @critica %>

<br>

<div>
  <%= link_to "Voltar aos comentários", criticas_path %>
</div>

app/views/criticas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @critica %>

<div>
  
  <%= link_to "Aprovar Comentário", edit_critica_path(@critica) %> |
  <%= link_to "Voltar aos comentários", criticas_path %>

  <%= button_to "Apagar comentário", @critica, method: :delete %>
</div>

app/views/filmes/_filme.html.erb
<div id="<%= dom_id filme %>">
  <p>
    <strong>Título:</strong>
    <%= filme.titulo %>
  </p>

  <p>
    <strong>Ano:</strong>
    <%= filme.ano_lancamento %>
  </p>

  <p>
    <strong>Elenco:</strong>
    <%= filme.ator_id %>
  </p>
  
   <!-- <strong>Comentários</strong <%=  %> > -->


</div>

app/views/filmes/_form.html.erb
<%= form_with(model: filme) do |form| %>
  <% if filme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(filme.errors.count, "error") %> prohibited this filme from being saved:</h2>

      <ul>
        <% filme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :"Título:", style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :"Ano de Lançamento:", style: "display: block" %>
    <%= form.number_field :ano_lancamento %>
  </div>

  <div>
    <%= form.label :"Elenco de atores:", style: "display: block" %>
     <%= form.select(:ator_id,@ator,{},{}) %>
  </div><br>

  <div>
  <button type="submit" class="btn btn-primary">Cadastrar</button>
  </div>
<% end %>

app/views/filmes/edit.html.erb
<div class="shadow-none p-3 mb-5 bg-light rounded">Editar Filme</div>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Show this filme", @filme %> |
  <%= link_to "Back to filmes", filmes_path %>
</div>

app/views/filmes/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="shadow-none p-3 mb-5 bg-light rounded">Filmes</div>


<div id="filmes">
  <% @filmes.each do |filme| %>
    <%= render filme %>
    <p>
      <%= link_to "Descrição do filme", filme %>
    </p>
  <% end %>
</div>

<%= link_to "Adicionar novo filme", new_filme_path %>

app/views/filmes/new.html.erb
<div class="shadow-none p-3 mb-5 bg-light rounded">Novo Filme</div>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Voltar", filmes_path %>
</div>

app/views/filmes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @filme %>

<div>
  <%= link_to "Editar filme", edit_filme_path(@filme) %> |
  <%= link_to "Voltar aos filmes", filmes_path %>
  <%= link_to "Fazer crítica", new_critica_path %>

  <%= button_to "Deletar filme", @filme, method: :delete %>
</div>

app/views/layouts/_menu.html.erb
<br>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Projeto 02</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="/filmes">Filmes</a>
        <a class="nav-link" href="/ators">Novo Ator</a>
        <a class="nav-link" href="/criticas">Críticas</a>
        <a class="nav-link" href="/logs">Logs</a>
        
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div> 
    </div>
    <%=render 'layouts/menu'%>
    <br>
    <div class="container">
    <h3>Catálogo de filmes - <%= Date.current.year %> </h3>
    <br>
    <%= yield %>
    <br>
    <div class="shadow-none p-3 mb-5 bg-light rounded">
    <footer class="text-center"> Inova Ação Afro | CESAR. </footer>
    </div>
    </div>
  </body>
</html>

app/views/logs/_form.html.erb
<%= form_with(model: log) do |form| %>
  <% if log.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this critica from being saved:</h2>

      <ul>
        <% log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table table-striped">
  <div>
    <%= form.label :comentario_id, style: "display: block" %>
    
  </div>

  <div>
    <%= form.label :created_at, style: "display: block" %>
    
  </div>
  </table>
  
<% end %>

app/views/logs/_log.html.erb
<div id="<%= dom_id log %>">
  <p>
    <strong>Comentario:</strong>
    <%= log.comentario_id %>
  </p>

  <p>
    <strong>Criado em:</strong>
    <%= log.created_at %>
  </p>

  </div>

app/views/logs/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="shadow-none p-3 mb-5 bg-light rounded">Logs</div>


<div id="logs">
  <% @logs.each do |log| %>
    <%= render log %>
    
  <% end %>
</div>